### ISSUE TITLE
Deciding upon open source data sets

### ISSUE THREAD

**Issue by kajaljadhav4494** [dnif/SOC18-genesis#1]
To brainstorm and search for data-source to get real time data-sets.

**Comment by anandam1992** [comment]
Following are some good datasources to follow and these datasources gets updated in realtime:

1.http://bruteforcers.net/
2.https://www.talosintelligence.com/vulnerability_reports#disclosed
3.http://malc0de.com/database/
4.https://www.scumware.org/
5.https://secure.dshield.org/ipsascii.html
6.https://sslbl.abuse.ch/blacklist/sslipblacklist.csv
7.http://osint.bambenekconsulting.com/feeds/c2-ipmasterlist.txt

**Comment by anandam1992** [comment]
After brainstorming and proper analysis of the datasources.
We have decided to go with http://bruteforcers.net/ .
Closing the issue as of now, we can reopen if necessary later on

**Comment by anandam1992** [comment]
![image](https://user-images.githubusercontent.com/37012140/40290830-7484ed08-5cde-11e8-8414-d9f8697ddb75.png)
