### ISSUE TITLE
Identifying the Queries to be used on the dataset and widgets to be used

### ISSUE THREAD

**Issue by anandam1992** [dnif/SOC18-genesis#14]

**Comment by anandam1992** [comment]
Sample queries are added to the repository and further help required as more data is accumulated

**Comment by SayaliSawant15** [comment]
**Graphical Representation for Dashboard:**
![dashboard](https://user-images.githubusercontent.com/33835459/40329543-827f4816-5d67-11e8-88de-0cfedd571392.png)

**Comment by anandam1992** [comment]
![image](https://user-images.githubusercontent.com/37012140/40331608-8ea8c37c-5d6e-11e8-9c0b-404e099c0353.png)
![image](https://user-images.githubusercontent.com/37012140/40331616-92f64cec-5d6e-11e8-9e41-2dfbb776253e.png)
![image](https://user-images.githubusercontent.com/37012140/40331624-9887ec42-5d6e-11e8-9bda-76493e3ec655.png)
![image](https://user-images.githubusercontent.com/37012140/40331630-9cff6ca0-5d6e-11e8-97ec-49750d0dc0c4.png)
![image](https://user-images.githubusercontent.com/37012140/40331633-a1a4877c-5d6e-11e8-9d91-d893859fcee5.png)
![image](https://user-images.githubusercontent.com/37012140/40331641-a5539af2-5d6e-11e8-8434-3a6eef9080d4.png)
![image](https://user-images.githubusercontent.com/37012140/40331649-aa996f46-5d6e-11e8-843f-12d56040c7c2.png)
![image](https://user-images.githubusercontent.com/37012140/40331654-aef68af6-5d6e-11e8-9de4-74aa648c5424.png)
![image](https://user-images.githubusercontent.com/37012140/40331662-b43487fc-5d6e-11e8-9a41-5b68d09ebbaf.png)
![image](https://user-images.githubusercontent.com/37012140/40331669-b81e4678-5d6e-11e8-9bb8-0a5a8ce19b9e.png)
![image](https://user-images.githubusercontent.com/37012140/40331674-bd30534a-5d6e-11e8-97a2-081db9825ffc.png)
![image](https://user-images.githubusercontent.com/37012140/40331681-c29fc838-5d6e-11e8-8ffa-bc7d3a24729d.png)
![image](https://user-images.githubusercontent.com/37012140/40331687-c7e14f06-5d6e-11e8-9e04-f24e6c00fc21.png)
![image](https://user-images.githubusercontent.com/37012140/40331696-cbf2f356-5d6e-11e8-8837-43d4f9b1fbf8.png)
![image](https://user-images.githubusercontent.com/37012140/40331704-d1273206-5d6e-11e8-8948-1e3333f25ed5.png)
![image](https://user-images.githubusercontent.com/37012140/40331710-d54a44a4-5d6e-11e8-8113-1bcadd3b1738.png)
![image](https://user-images.githubusercontent.com/37012140/40331717-d9415a34-5d6e-11e8-8f9e-e219a7d7b1ca.png)
![image](https://user-images.githubusercontent.com/37012140/40331722-dd19eb6c-5d6e-11e8-9773-73b40e3c5ea6.png)
