### ISSUE TITLE
Step-by-Step User Guideline to Upload data to DNIF Console using POSTMAN Application

### ISSUE THREAD

**Issue by SayaliSawant15** [dnif/SOC18-genesis#17]
Refer the following document:
[Detailed Document for Posting data to DNIF using POSTMAN Application.docx](https://github.com/dnif/SOC18-genesis/files/2006942/Detailed.Document.for.Posting.data.to.DNIF.using.POSTMAN.Application.docx)
for reference.

**Comment by anandam1992** [comment]
Required document is added in the Static Folder.
