### ISSUE TITLE
Convert Json log file to CSV

### ISSUE THREAD

**Issue by kajaljadhav4494** [dnif/SOC18-genesis#3]
Json log file are not in simple json file so converting using simple python or tools is bit difficult as they can only parse simple json .

Json file url-
http://www.gstatic.com/ddos-viz/attacks_v2.json

**Comment by anandam1992** [comment]
Since the dataset has been changed the new url is : http://bruteforcers.net/

**Comment by anandam1992** [comment]
The code is added in the repository
