### ISSUE TITLE
Digrammatic Representation of Project

### ISSUE THREAD

**Issue by SayaliSawant15** [dnif/SOC18-genesis#5]
Need to clearly understand the process to be followed for project process with the help of a graphical representation as shown below.

![process](https://user-images.githubusercontent.com/33835459/39711316-09db6e06-523d-11e8-8975-175ccc03622d.png)

**Comment by anandam1992** [comment]
Taking reference from : https://github.com/dnif/DigiVigi/issues/1

![39574485-0dad9fae-4ef5-11e8-96c9-2aba1e6ff108](https://user-images.githubusercontent.com/37012140/39762823-40ca3a2a-52f9-11e8-8a7b-9807842227d1.png)

![process](https://user-images.githubusercontent.com/37012140/39762832-475f2eea-52f9-11e8-9216-736265034fae.png)

**Comment by anandam1992** [comment]
Code Diagrams and Pics
![image](https://user-images.githubusercontent.com/37012140/40293406-6e686e12-5cee-11e8-91b3-9146c9aad6f5.png)
![image](https://user-images.githubusercontent.com/37012140/40293412-78ec4502-5cee-11e8-9a66-b2164690f4de.png)
![image](https://user-images.githubusercontent.com/37012140/40293417-7f3a648e-5cee-11e8-93c1-a37cc85c7244.png)
![image](https://user-images.githubusercontent.com/37012140/40293428-8493cc72-5cee-11e8-89fb-913045310132.png)
![image](https://user-images.githubusercontent.com/37012140/40293432-8e35c0f0-5cee-11e8-9b2a-a09e6e1c3abb.png)
![image](https://user-images.githubusercontent.com/37012140/40293438-9428d43e-5cee-11e8-96b2-688bb0b24feb.png)
![image](https://user-images.githubusercontent.com/37012140/40293447-a0ed75bc-5cee-11e8-9beb-d580ebb2ecd7.png)
![image](https://user-images.githubusercontent.com/37012140/40293455-a916879c-5cee-11e8-8295-171a66358da8.png)
![image](https://user-images.githubusercontent.com/37012140/40293460-ae55a6f2-5cee-11e8-9342-bdb5e3374247.png)

**Comment by anandam1992** [comment]
INTEGRATING LIVE WEBSITE DATA WITH DNIF
![image](https://user-images.githubusercontent.com/37012140/40294206-3f875b36-5cf2-11e8-924a-1ee4c447ad69.png)

**Comment by anandam1992** [comment]
Postman
![image](https://user-images.githubusercontent.com/37012140/40294522-949dd5e0-5cf3-11e8-9da0-96ec3dff06e3.png)

![image](https://user-images.githubusercontent.com/37012140/40294631-091e8702-5cf4-11e8-8dd5-39cbf3c0242d.png)

![image](https://user-images.githubusercontent.com/37012140/40294665-2ed0b7b8-5cf4-11e8-8cc2-ca5a4da79863.png)

![image](https://user-images.githubusercontent.com/37012140/40294732-70628eae-5cf4-11e8-95e2-0ca7e0d05531.png)

![image](https://user-images.githubusercontent.com/37012140/40294797-a858bb30-5cf4-11e8-964a-385052b0f369.png)

![image](https://user-images.githubusercontent.com/37012140/40294839-d373cc92-5cf4-11e8-938d-485228b312c6.png)

![image](https://user-images.githubusercontent.com/37012140/40294879-f8f791c4-5cf4-11e8-82fa-28023bf76ad6.png)

![image](https://user-images.githubusercontent.com/37012140/40294982-54008fbc-5cf5-11e8-82ab-118545ab13ba.png)

**Comment by anandam1992** [comment]
![image](https://user-images.githubusercontent.com/37012140/40295129-e0cd2ac2-5cf5-11e8-9184-8ddee7c5744e.png)
![image](https://user-images.githubusercontent.com/37012140/40295134-e4ce0718-5cf5-11e8-9951-65545c8033b7.png)
![image](https://user-images.githubusercontent.com/37012140/40295139-e86d9942-5cf5-11e8-8422-a419dae00d26.png)
![image](https://user-images.githubusercontent.com/37012140/40295143-ece37c80-5cf5-11e8-8e30-ad9aeba75cb7.png)
![image](https://user-images.githubusercontent.com/37012140/40295146-f1364358-5cf5-11e8-825b-5f78501e4c51.png)
![image](https://user-images.githubusercontent.com/37012140/40295150-f6264606-5cf5-11e8-8a00-aeeea9af5a65.png)
![image](https://user-images.githubusercontent.com/37012140/40295156-facbc5e6-5cf5-11e8-9e61-9834cbf72c44.png)
![image](https://user-images.githubusercontent.com/37012140/40295161-fffb1f08-5cf5-11e8-8a76-56fd3ceabdac.png)
![image](https://user-images.githubusercontent.com/37012140/40295166-04239f92-5cf6-11e8-8f51-95e4150020eb.png)
![image](https://user-images.githubusercontent.com/37012140/40295172-0897e4c0-5cf6-11e8-95b8-cd1e89208dd5.png)

**Comment by anandam1992** [comment]
![image](https://user-images.githubusercontent.com/37012140/40295129-e0cd2ac2-5cf5-11e8-9184-8ddee7c5744e.png)
![image](https://user-images.githubusercontent.com/37012140/40295134-e4ce0718-5cf5-11e8-9951-65545c8033b7.png)
![image](https://user-images.githubusercontent.com/37012140/40295139-e86d9942-5cf5-11e8-8422-a419dae00d26.png)
![image](https://user-images.githubusercontent.com/37012140/40295143-ece37c80-5cf5-11e8-8e30-ad9aeba75cb7.png)
![image](https://user-images.githubusercontent.com/37012140/40295146-f1364358-5cf5-11e8-825b-5f78501e4c51.png)
![image](https://user-images.githubusercontent.com/37012140/40295150-f6264606-5cf5-11e8-8a00-aeeea9af5a65.png)
![image](https://user-images.githubusercontent.com/37012140/40295156-facbc5e6-5cf5-11e8-9e61-9834cbf72c44.png)
![image](https://user-images.githubusercontent.com/37012140/40295161-fffb1f08-5cf5-11e8-8a76-56fd3ceabdac.png)
![image](https://user-images.githubusercontent.com/37012140/40295166-04239f92-5cf6-11e8-8f51-95e4150020eb.png)
![image](https://user-images.githubusercontent.com/37012140/40295172-0897e4c0-5cf6-11e8-95b8-cd1e89208dd5.png)

**Comment by anandam1992** [comment]
![a](https://user-images.githubusercontent.com/37012140/41401076-853ebbe0-6fdc-11e8-8320-d63fd39f88ec.jpg)

**Comment by anandam1992** [comment]
![a](https://user-images.githubusercontent.com/37012140/41401211-d808477e-6fdc-11e8-8aca-45f103712c31.jpg)

**Comment by anandam1992** [comment]
![a](https://user-images.githubusercontent.com/37012140/41403328-3bd7e912-6fe2-11e8-9078-41d3409d2dba.jpg)
![b](https://user-images.githubusercontent.com/37012140/41403339-41cba020-6fe2-11e8-9796-95c5ae966066.jpg)

**Comment by anandam1992** [comment]
![b](https://user-images.githubusercontent.com/37012140/41403658-070f5ebc-6fe3-11e8-8998-47a49f24740d.jpg)
![c](https://user-images.githubusercontent.com/37012140/41404265-5e2c1310-6fe4-11e8-8374-e14c62e9262b.jpg)
![c](https://user-images.githubusercontent.com/37012140/41404355-a021150e-6fe4-11e8-8bc3-b632f267f655.jpg)

**Comment by anandam1992** [comment]
![header](https://user-images.githubusercontent.com/37012140/41414406-8148013c-7003-11e8-833f-45236b9a1a23.jpg)

**Comment by anandam1992** [comment]
![header](https://user-images.githubusercontent.com/37012140/41414727-756d088e-7004-11e8-93cf-bc74401d0bf5.jpg)
