### ISSUE TITLE
Configuring Email Notification with SMTP

### ISSUE THREAD

**Issue by kajaljadhav4494** [dnif/SOC18-genesis#6]
Currently working on configuring SMTP server in DNIF container to send alerts raised on DNIF Web Console to Email addresses.

**Comment by anandam1992** [comment]
Following the steps in : https://dnif.it/docs/guides/tutorials/configuring-smtp-in-docker.html

**Comment by SayaliSawant15** [comment]
Resolved SMTP configuration issue as per the steps mentioned below: 
![smtp configuration guideline on dnif](https://user-images.githubusercontent.com/33835459/40626218-ac23a492-62d4-11e8-9089-fb67c7f693f8.png)
