### ISSUE TITLE
Facing issue while parsing data from data-set by country and organization

### ISSUE THREAD

**Issue by kajaljadhav4494** [dnif/SOC18-genesis#7]

**Comment by anandam1992** [comment]
The problem of parsing was due to the presence of commas once converted into csv files (comma separated values) . So as the name suggests if there is comma present in the following strings, the strings gets separated into 2 columns causing the issue.

**Comment by anandam1992** [comment]
As per the new updated code, the problem has been solved by replacing the commas (,) in the strings to dot (.) which solves the problem. Below is the snippet of the code

        Country_w= table_rows[a].find_all('td')[4].get_text().strip()
        #Avoiding "," as its is using it as delimeter in a csv(comma seperated value)
        Country= Country_w.replace(',', '.')
        Organization_w= table_rows[a].find_all('td')[5].get_text().strip()
        #Avoiding "," as its is using it as delimeter in a csv(comma seperated value)
        Organization=Organization_w.replace(',', '.')

Had gone through thorough discussions about the same within team. We will reopen the issue if similar problem comes up,
