### ISSUE TITLE
Problem with SMTP authentication

### ISSUE THREAD

**Issue by anandam1992** [dnif/SOC18-genesis#8]
Following the below link for the configuration SMTP in Docker:
https://dnif.it/docs/guides/tutorials/configuring-smtp-in-docker.html

Facing problems due to authentication and network time out.

**Comment by SayaliSawant15** [comment]
Resolved issue for SMTP Configuration with DNIF as per the steps mentioned below:

![smtp configuration guideline on dnif](https://user-images.githubusercontent.com/33835459/40626218-ac23a492-62d4-11e8-9089-fb67c7f693f8.png)
